name: CI/CD Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew clean build -x test

    - name: Upload JAR to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2DEPLOYONE }}
        source: "build/libs/*.jar"
        target: "/home/ubuntu/projects"

    - name: SSH Deploy on EC2 using systemd
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2DEPLOYONE }}
        script: |
          cd /home/ubuntu/projects
          
          # ✅ Find newest JAR file
          JAR_FILE=$(ls -t *.jar | head -n 1)
          
          # ✅ Update systemd ExecStart to latest jar
          sudo sed -i "s|ExecStart=.*|ExecStart=/usr/bin/java -jar /home/ubuntu/projects/$JAR_FILE|" /etc/systemd/system/springboot.service
          
          # ✅ Restart service properly
          sudo systemctl daemon-reload
          sudo systemctl restart springboot
          
          # ✅ Show service status
          sudo systemctl status springboot --no-pager
